version: "3.8"

services:
  unoserver:
    image: libreofficedocker/libreoffice-unoserver:3.19-9c28c22
    ports:
      - "2004:2004"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/code/app # mount code for live edit
    ports:
      - "8000:8000"
    depends_on:
      - unoserver
      - minio

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # MinIO Console UI
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data

volumes:
  minio_data:
